services:
  app:
    build: .
    container_name: codefact-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - codefact-db

  codefact-db:
    image: postgres:14-alpine
    container_name: codefact-db
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
    external: true