services:
  app:
    build: .
    container_name: codefact-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - codefact-db

  codefact-db:
    image: postgres:14-alpine
    container_name: codefact-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true